name: "Deploy Web App with Docker Compose"

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**' # 🎯 Skips this pipeline if you only edit cloud infrastructure files

jobs:
  deploy:
    name: "Deploy Multi-Container App via SSH"
    runs-on: ubuntu-latest

    steps:
      - name: Execute Remote Docker Compose Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}             # Your permanent static Elastic IP
          username: ${{ secrets.EC2_USERNAME }}     # ubuntu
          key: ${{ secrets.CAPSTONE_SSH }}         # Your secure custom private key
          script: |
            # 1. Clone the project repository if it is the first run, otherwise pull latest changes
            if [ ! -d "~/cloud-engineer-capstone" ]; then
              git clone https://github.com/pyaephyo47/cloud-engineer-capstone.git ~/cloud-engineer-capstone 
            fi
            
            cd ~/cloud-engineer-capstone 
            git pull origin main

            # 3. Bring down any old compose stack deployments cleanly
            docker compose down || true

            # 4. Build and boot your fresh multi-container app stack in the background
            docker compose up -d --build
