name: Deploy Web App to EC2

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.CAPSTONE_SSH }}
          script: |
            if [ ! -d "~/cloud-engineer-capstone" ]; then
              git clone https://github.com/pyaephyo47/cloud-engineer-capstone.git
            fi
            cd ~/cloud-engineer-capstone 
            git pull origin main
            docker stop capstone-site || true
            docker rm capstone-site || true
            docker build -t capstone-app .
            docker run -d -p 80:80 --name capstone-site capstone-app
